@startuml example-c4-modell-diagram
' source: https://github.com/plantuml-stdlib/C4-PlantUML
' C4 Model
!include <c4/C4_Context.puml>

' Images
!include <office/Users/user.puml>
!include <office/Users/mobile_user.puml>

' Diagram title
title \nSystem Context diagram for Cocktail Delivery System\n

' Diagram syntax
Person(customer, Customer, "<$user> <$mobile_user>\n A customer of cocktail-delivery-service")
Enterprise_Boundary(c0, "Cocktail Bar") {
  System(webshop_system, "Cocktail Delivery Webshop", "Allows customers to view and order cocktails")

  'SystemDb(database, "Database", "Stores all of the core information about customers, accounts, transactions, ingredients.")
}
System_Ext(pay_system, "Payment System", "Processes cocktail payment")

Rel(customer, webshop_system, "Uses")
Rel_Back(webshop_system, pay_system, "Gets successfully payment data back")
Rel_Neighbor(webshop_system, pay_system, "Sends JSON data")
'Rel(webshop_system, database, "Uses")
@enduml